spring:
  datasource:
    url: jdbc:mysql://localhost:3308/vendasnew?useTimezone=true&serverTime
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      username: root
      password: Light100!

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true